Life1=3
print("|===================================|")
print("|----Quien Quiere-Ser Millonario----|")
print("|¿Estas listo para las preguntas...?|")
print("|===================================|")
print("")
input("¿Si o no? ")
print("")
print("Nah!! era mentira, estes listo o no alla vamos nene!!")
print("Por cierto tienes 3 vidas")
print("")
print("")
print("==========================Primera-pregunta=========================")
print("")
print("Cuando salio por primera vez la Nes 'Nintendo Entertainment System'")
print("")
print("A) 1980       b) 1996")
print("C) 1975       b) 1983")
